### ISSUE TITLE
External creation of ILifetimeScope

### ISSUE THREAD

**Issue by srogovtsev** [autofac/Autofac.Owin#10]
I have a particular configuration (i.e., hosting OWIN in plain vanilla asp.net application in IIS) that requires me to "inject" `ILifetimeScope` from outside OWIN middleware instead of creating it inside. So what I want to have is:

1. asp.net's `Application_BeginRequest` creates a per-request lifetime scope and saves it to `HttpRequest` properties
2. OWIN injector middleware, instead of creating its own lifetime scope, calls external "factory", which simply extracts lifetime scope from `HttpRequest` properties
3. further OWIN pipeline proceeds as before
4. because lifetime scope was created externally, OWIN injector middleware does not dispose it
5. asp.net's `Application_EndRequest` gets lifetime scope from `HttpRequest` properties and disposes it

Is this a feasible approach? I can provide a create a pull-request for this quite quickly and I don't think this would be a breaking change.

**Comment by tillig** [comment]
Why not just insert your own middleware that creates the lifetime scope into the pipeline _before_ the Autofac middleware runs? [OWIN won't create a lifetime scope if it's already present.](https://github.com/autofac/Autofac.Owin/blob/develop/src/Autofac.Integration.Owin/AutofacMiddleware.cs#L45)

You could basically copy/paste the AutofacMiddleware class, have it call your factory, and then add it to the pipeline prior to the AutofacMiddleware itself being added.

**Comment by srogovtsev** [comment]
`Constants.OwinLifetimeScopeKey` [is `internal`](https://github.com/autofac/Autofac.Owin/blob/develop/src/Autofac.Integration.Owin/Constants.cs#L43), so I can't inject the scope myself.

(yes, actually the minimal change that allows me to fix the problem is to simply make it `public`)

**Comment by tillig** [comment]
What if we added `context.SetAutofacLifetimeScope(ILifetimeScope scope)`?

**Comment by srogovtsev** [comment]
This would be nice! But `UseMiddlewareFromContainer` checks for injector registration, so you'd have to provide something like `app.MarkInjectorAsRegistered` as well - which is not a problem by me, of course.

So the whole startup would look like this:

```
app
   .Use((ctx, next) =>
   {
      ctx.SetAutofacLifetimeScope(myScopeGetter());
      return next();
   }
   .MarkInjectorRegistered()
   .UseMiddlewareFromContainer<MyMiddleware>();
```

**Comment by tillig** [comment]
Couldn't we just add a null check [here](https://github.com/autofac/Autofac.Owin/blob/develop/src/Autofac.Integration.Owin/AutofacAppBuilderExtensions.cs#L329)? Like, if lifetime scope isn't already set, create it; otherwise just don't do anything.

**Comment by tillig** [comment]
Also, when did you want to dispose of the scope? If you set your own scope, would that mean you're responsible for disposing it? (I'm guessing so.) In that case, it'd be like "if the scope is set, just await `next()` otherwise do the using/create lifetime scope thing."

**Comment by srogovtsev** [comment]
Yes, I want to be responsible for scope disposal. So, you mean the startup would look like

```
app
   .Use((ctx, next) =>
   {
      ctx.SetAutofacLifetimeScope(myScopeGetter());
      return next();
   }
   .UseAutofacLifetimeScopeInjector(rootContainer)
   .UseMiddlewareFromContainer<MyMiddleware>();
```

...and `UseAutofacLifetimeScopeInjector` (`RegisterAutofacLifetimeScopeInjector`, in fact) will check whether the scope exists, and if it does, will simply call `next()` instead of creating/disposing its own scope?

Totally fine by me.

**Comment by srogovtsev** [comment]
Should I draft up a pull-request for this?

**Comment by tillig** [comment]
Sure, that'd rock.

**Comment by srogovtsev** [comment]
I ended up creating two pull requests, for different variants of syntax (for all I know, you can adopt both, they do not contradict each other).

**Comment by tillig** [comment]
I think both enhancements are good. I'll pull them both in. You rock! Thanks!

**Comment by tillig** [comment]
I have both PRs merged and semver updated to 4.1.0. Building, published to MyGet, ready to go. You mentioned you wanted to do one more look at the code to make sure it's all good, so please do and let me know if there are more changes or if it's ready.

If it's ready, I'll push it as 4.1.0 to NuGet and close this issue.

**Comment by srogovtsev** [comment]
I'll try to review it within a couple of hours.

**Comment by srogovtsev** [comment]
Done it, see #13. Sorry it took me so long, I've finally remembered what it was that I wanted to add on Saturday - an extension method to compensate for the fact that externally created lifetime scope doesn't have `IOwinContext` registered.

**Comment by tillig** [comment]
[Pushed to NuGet as 4.1.0](https://www.nuget.org/packages/Autofac.Owin/4.1.0). Thanks again!
