### ISSUE TITLE
.NET Standard / .NET Core support?

### ISSUE THREAD

**Issue by ViktorHofer** [autofac/Autofac.Owin#15]
I see that the TFM of the nuget package is net45: https://www.nuget.org/packages/Autofac.Owin/

Is .NET Standard / .NET Core support planned? If not, do you need help for that?

Thanks,
Viktor

**Comment by tillig** [comment]
OWIN isn't a thing in .NET standard. They changed the whole model for ASP.NET Core. So, no, there is no support planned.

**Comment by macca16** [comment]
It may not be an owin issue but I'm unable to use .NET Standard 2 library projects within a MVC 5 or WebApi2 project and I believe it may be due to this issue

**Comment by tillig** [comment]
I would recommend creating a reproduction to verify that - an MVC 5 project that doesn't use Autofac but does use netstandard 2.0.

**Comment by macca16** [comment]
Hi, we tried using the sample project for autofac and had no issues. Our problem seems to actually be this one https://github.com/dotnet/corefx/issues/28833

Thanks
