### ISSUE TITLE
7.0.0 introduced memory leak due to async disposal issue in main Autofac

### ISSUE THREAD

**Issue by srogovtsev** [autofac/Autofac.Owin#34]
I want to file this here just so that the people Googling for the symptoms will be able to find it and see the resolution

## Describe the Bug

After upgrading to `Autofac.Owin` 7.0.0 we've observed a sizeable memory leak due to a lot of held `System.Threading.ThreadLocal+LinkedSlotVolatile<System.Collections.Concurrent.ConcurrentBag+ThreadLocalList<Autofac.Core.IComponentRegistration>>`

## Steps to Reproduce

* Setup a regular OWIN integration: `app.UseAutofacLifetimeScopeInjector(_container)`
* See autofac/Autofac#1252

## Expected Behavior

* no memory leak

## Dependency Versions

`Autofac`: 6.4.0
`Autofac.Owin`: 7.0.0

## Additional Info

* The [7.0.0 release](https://github.com/autofac/Autofac.Owin/releases/tag/v7.0.0) introduced a support for `IAsyncDisposable` (see #29).
* This support [switches](https://github.com/autofac/Autofac.Owin/pull/29/files#diff-6528a1c8bfa8a2ea8d2ac87430e999a359be0c3e570253e0b772f69997bacc63R393) from `IDisposable` to `IAsyncDisposable` to dispose `ILifetimeScope`
* The memory leak for `IDisposable` was fixed in autofac/Autofac#1257, **but** the `IAsyncDisposable` wasn't fixed: autofac/Autofac#1353

So, to fix this, we simply need to wait for new core release, and then simply bump the required dependency version.

**Comment by tillig** [comment]
@alistairjevans Do you think we're ready for a 6.5.0 release on core Autofac? I vaguely recall you were trying to get some more of the cache fixup work done but it may be at a point where it's stable enough to get out what's there.

**Comment by alistairjevans** [comment]
Yeah, it may have to go out without the isolated scope changes (no harm doing so really); I'd been hoping to get back to them sooner, but have been absolutely slammed at the day job.

**Comment by tillig** [comment]
Just to verify - some of the changes to support that _did_ get merged in even if the whole feature isn't complete. I just wanted to make sure you think it's stable enough as it is to go out; I sort of got confused following all of it. I can try cutting a 6.5.0 if you're good with it.

**Comment by alistairjevans** [comment]
Yeah, the changes around reflection-cache-clearing went in and are stable I believe.

The pending PR is needed to truly close off the isolated-scope-for-loaded-assembly issue, but the changes as they stand are still good.

**Comment by tillig** [comment]
OK, I'll see if I can cut a 6.5.0. Probably tomorrow.

**Comment by srogovtsev** [comment]
Will you be pushing out a new version of this package as well, with version-bumped dependency?

**Comment by tillig** [comment]
I hadn't planned on it but I can. It won't be today.

**Comment by srogovtsev** [comment]
Oh no, if you hadn't planned, don't bother, I just wanted to know if we'd have one more upgrade in the queue. We can simply bump Autofac version on our end.

**Comment by tillig** [comment]
Autofac.Owin has a version _range_ dependency right now:

`<PackageReference Include="Autofac" Version="[6.0.0, 7.0.0)" />`

which is [reflected on nuget.org as well](https://www.nuget.org/packages/Autofac.Owin#dependencies-body-tab).

Thus, I think _the actual solution_ is to update on the client end. There's no new package here to issue.

I'm going to close this for now under the assumption things are going to work out. If there's some other action we need to take, post and we can reopen the ticket. Thanks!
