### ISSUE TITLE
Only Microsoft.Owin.Middleware

### ISSUE THREAD

**Issue by johnkors** [autofac/Autofac.Owin#7]
Hi guys!

Does this package only work for middleware that inherit from ```Microsoft.Owin.OwinMiddleware```? 

Sample:
https://github.com/johnkors/Autofac.OwinMiddleware.Sample/tree/master

Just wondering, seeing as there are several ways of implementing middlewares..
http://benfoster.io/blog/how-to-write-owin-middleware-in-5-different-steps

**Comment by tillig** [comment]
Yes, only `Microsoft.Owin.OwinMiddleware`. You can see the type constraint here: https://github.com/autofac/Autofac.Owin/blob/master/src/Autofac.Integration.Owin/AutofacMiddleware.cs

**Comment by johnkors** [comment]
As well as here, I presume : https://github.com/autofac/Autofac.Owin/blob/master/src/Autofac.Integration.Owin/AutofacAppBuilderExtensions.cs#L308

Will have to do a quick rewrite of my mw's then. Thanks for the quick reply :+1:
